# Generated by Django 5.0.2 on 2024-02-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_weatherdata_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='coord',
            new_name='Coordinate',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='country_code',
            new_name='Country_code',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='humidity',
            new_name='Humidity',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='pressure',
            new_name='Pressure',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='temp',
            new_name='Temperature',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='timestamp',
            new_name='Timestamp',
        ),
    ]
