# Generated by Django 5.0.2 on 2024-02-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_city_weatherdata_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='Coordinate',
            new_name='coord',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='Country_code',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='Humidity',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='Pressure',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='Temperature',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
